using SubnauticaModManager.Files;
using System.Text;

namespace SubnauticaModManager.Mono;

internal class GetModListButton : MonoBehaviour
{
    private const string kFileName = "mod-list.txt";

    private static string TextFileLocation => Path.Combine(FileManagement.ModManagerFolder, kFileName);

    private void Start()
    {
        var button = GetComponent<Button>();
        button.onClick = new Button.ButtonClickedEvent();
        button.onClick.AddListener(() => OnClick());
    }

    private void OnClick()
    {
        StringBuilder sb = new();
        ConstructModList(sb);
        File.WriteAllText(TextFileLocation, sb.ToString());
        Application.OpenURL(TextFileLocation);
    }

    private static void ConstructModList(StringBuilder sb)
    {
        sb.AppendLine($"Mod list generated by {Plugin.Name} v{Plugin.Version}");
        sb.AppendLine();

        var modList = KnownPlugins.list;
        foreach (var mod in modList)
        {
            if (mod != null)
            {
                sb.Append(mod.Name);
                sb.Append(" | ");
                sb.Append(mod.GUID);
                sb.Append(" | v");
                sb.Append(mod.Version);
                sb.Append(" | ");
                sb.Append(mod.GetStatus(modList).FormatPluginStatus(ModEnablement.GetEnableState(mod)));
                sb.AppendLine();
                sb.AppendLine();
            }
        }
    }
}